pipeline:
    0_protein_scorer:
        weight: 1
        threshold: 5 #in grams
    1_fiber_scorer:
        weight: 3
        threshold: 10 #in grams
    2_fat_scorer:
        weight: 2
        threshold: 1 #in grams
    3_caloric_scorer:
        weight: 1
        threshold: 10 #in kcal
        protein_cal_per_gram: 4 #kcal
        fat_cal_per_gram: 9 #kcal
        fiber_cal_per_gram: 2 #kcal